---
apiVersion: v1
kind: Namespace
metadata:
  name: xnf-5g-cu-seattle
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pod2-certs-seattle-cu
  namespace: xnf-5g-cu-seattle
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: "aWJtdXNlcg=="
  secretKey: "aWJtcGFzc3dvcmQ="
